apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "rucio.fullname" . }}-auth
  labels:
    app: {{ template "rucio.name" . }}-auth
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.authReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}-auth
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}-auth
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: aliases
        configMap:
          name: {{ template "rucio.fullname" . }}-auth-aliases
      - name: httpdlog
        emptyDir: {}
{{- if .Values.authServer.useSSL }}
      - name: hostcert
        secret:
          secretName: host-cert
      - name: hostkey
        secret:
          secretName: host-key
      - name: cafile
        secret:
          secretName: ca
{{- end }}
      containers:
{{- if .Values.exposeErrorLogs.authServer }}
        - name: httpd-error-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -f /var/log/httpd/error_log']
          volumeMounts:
          - name: httpdlog
            mountPath: /var/log/httpd
{{- end }}
        - name: {{ .Chart.Name }}-auth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
{{- if .Values.config }}
{{- if .Values.config.database }}
{{- $sql_impl := substr 0 5 (toString .Values.config.database.default) -}}
{{- if eq "mysql" $sql_impl}}
          lifecycle:
            postStart:
              exec:
                command: ["/usr/bin/yum", "install", "MySQL-python", "-y",]
{{- end }}
{{- end }}
{{- end }}
          volumeMounts:
            - name: httpdlog
              mountPath: /var/log/httpd
            - name: aliases
              mountPath: /opt/rucio/etc/aliases.conf
              subPath: aliases.conf
{{- if .Values.authServer.useSSL }}
            - name: hostcert
              mountPath: /etc/grid-security/hostcert.pem
              subPath: hostcert.pem
            - name: hostkey
              mountPath: /etc/grid-security/hostkey.pem
              subPath: hostkey.pem
            - name: cafile
              mountPath: /etc/grid-security/ca.pem
              subPath: ca.pem
{{- end }}
          env:
            {{- range $key1, $val1 := .Values.config }}
            {{- range $key2, $val2 := $val1}}
            - name: RUCIO_CFG_{{ $key1 | upper }}_{{ $key2 | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key1 }}_{{ $key2 }}
            {{- end}}
            {{- end}}
{{- if .Values.authServer.useSSL }}
            - name: RUCIO_ENABLE_SSL
              value: "True"
            - name: OPENSSL_ALLOW_PROXY_CERTS
              value: "1"
            - name: RUCIO_CA_PATH
              value: "/etc/grid-security/certificates"
{{- else }}
            - name: RUCIO_ENABLE_SSL
              value: "False"
{{- end }}
            - name: RUCIO_DEFINE_ALIASES
              value: "True"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
