name: rucio-server
version: 0.5.1
apiVersion: v1
description: A Helm chart to deploy servers for Rucio
keywords:
  - data-management
  - science
home: https://rucio.cern.ch/
sources:
  - https://github.com/arisfkiaras/rucio
maintainers:
  - name: Thomas Beermann
    email: thomas.beermann@cern.ch

